FROM node:24-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install prisma
RUN pnpm add prisma

# Copy prisma schema
COPY prisma ./prisma

# Run migration
CMD ["pnpm", "exec", "prisma", "migrate", "deploy"]